export default {
  'fonts': [
    {'name': 'Al Bayan'},
    {'name': 'Al Nile'},
    {'name': 'Al Tarikh'},
    {'name': 'American Typewriter'},
    {'name': 'Andale Mono'},
    {'name': 'Apple Braille'},
    {'name': 'Apple Chancery'},
    {'name': 'Apple Color Emoji'},
    {'name': 'Apple LiGothic'},
    {'name': 'Apple LiSung'},
    {'name': 'Apple SD Gothic Neo'},
    {'name': 'Apple Symbols'},
    {'name': 'AppleGothic'},
    {'name': 'AppleMyungjo'},
    {'name': 'Arial'},
    {'name': 'Arial Black'},
    {'name': 'Arial Hebrew'},
    {'name': 'Arial Hebrew Scholar'},
    {'name': 'Arial Narrow'},
    {'name': 'Arial Rounded MT Bold'},
    {'name': 'Arial Unicode MS'},
    {'name': 'Athelas'},
    {'name': 'Avant Garde'},
    {'name': 'Avenir'},
    {'name': 'Avenir Next'},
    {'name': 'Avenir Next Condensed'},
    {'name': 'Ayuthaya'},
    {'name': 'Baghdad'},
    {'name': 'Bangla MN'},
    {'name': 'Bangla Sangam MN'},
    {'name': 'Baoli SC'},
    {'name': 'Baoli TC'},
    {'name': 'Baskerville'},
    {'name': 'Beirut'},
    {'name': 'BiauKai'},
    {'name': 'Big Caslon'},
    {'name': 'Bodoni 72'},
    {'name': 'Bodoni 72 Oldstyle'},
    {'name': 'Bodoni 72 Smallcaps'},
    {'name': 'Bodoni MT'},
    {'name': 'Bodoni Ornaments'},
    {'name': 'Book Antiqua'},
    {'name': 'Bookman'},
    {'name': 'Bookman Old Style'},
    {'name': 'Bradley Hand'},
    {'name': 'Brush Script MT'},
    {'name': 'Calibri'},
    {'name': 'Calisto MT'},
    {'name': 'Cambria'},
    {'name': 'Candara'},
    {'name': 'Century Gothic'},
    {'name': 'Chalkboard'},
    {'name': 'Chalkboard SE'},
    {'name': 'Chalkduster'},
    {'name': 'Charter'},
    {'name': 'Cochin'},
    {'name': 'Comic Sans MS'},
    {'name': 'Consolas'},
    {'name': 'Copperplate'},
    {'name': 'Corsiva Hebrew'},
    {'name': 'Courier'},
    {'name': 'Courier New'},
    {'name': 'Damascus'},
    {'name': 'DecoType Naskh'},
    {'name': 'Devanagari MT'},
    {'name': 'Devanagari Sangam MN'},
    {'name': 'Didot'},
    {'name': 'DIN Alternate'},
    {'name': 'DIN Condensed'},
    {'name': 'Diwan Kufi'},
    {'name': 'Diwan Thuluth'},
    {'name': 'Droid Sans'},
    {'name': 'Euphemia UCAS'},
    {'name': 'Farah'},
    {'name': 'Farisi'},
    {'name': 'Franklin Gothic Medium'},
    {'name': 'Futura'},
    {'name': 'Garamond'},
    {'name': 'GB18030 Bitmap'},
    {'name': 'Geeza Pro'},
    {'name': 'Geneva'},
    {'name': 'Georgia'},
    {'name': 'Gill Sans'},
    {'name': 'Goudy Old Style'},
    {'name': 'Gujarati MT'},
    {'name': 'Gujarati Sangam MN'},
    {'name': 'GungSeo'},
    {'name': 'Gurmukhi MN'},
    {'name': 'Gurmukhi MT'},
    {'name': 'Gurmukhi Sangam MN'},
    {'name': 'Hannotate SC'},
    {'name': 'Hannotate TC'},
    {'name': 'HanziPen SC'},
    {'name': 'HanziPen TC'},
    {'name': 'HeadLineA'},
    {'name': 'Hei'},
    {'name': 'Heiti SC'},
    {'name': 'Heiti TC'},
    {'name': 'Helvetica'},
    {'name': 'Helvetica Neue'},
    {'name': 'Herculanum'},
    {'name': 'Hiragino Kaku Gothic Pro'},
    {'name': 'Hiragino Kaku Gothic ProN'},
    {'name': 'Hiragino Kaku Gothic Std'},
    {'name': 'Hiragino Kaku Gothic StdN'},
    {'name': 'Hiragino Maru Gothic Pro'},
    {'name': 'Hiragino Maru Gothic ProN'},
    {'name': 'Hiragino Mincho Pro'},
    {'name': 'Hiragino Mincho ProN'},
    {'name': 'Hiragino Sans'},
    {'name': 'Hiragino Sans CNS'},
    {'name': 'Hiragino Sans GB'},
    {'name': 'Hoefler Tex'},
    {'name': 'Hoefler Text'},
    {'name': 'Impact'},
    {'name': 'InaiMathi'},
    {'name': 'Iowan Old Style'},
    {'name': 'ITF Devanagari'},
    {'name': 'ITF Devanagari Marathi'},
    {'name': 'Kai'},
    {'name': 'Kailasa'},
    {'name': 'Kaiti SC'},
    {'name': 'Kaiti TC'},
    {'name': 'Kannada MN'},
    {'name': 'Kannada Sangam MN'},
    {'name': 'Kefa'},
    {'name': 'Khmer MN'},
    {'name': 'Khmer Sangam MN'},
    {'name': 'Klee'},
    {'name': 'Kohinoor Bangla'},
    {'name': 'Kohinoor Devanagari'},
    {'name': 'Kohinoor Telugu'},
    {'name': 'KohinoorBangla-Regular'},
    {'name': 'Kokonor'},
    {'name': 'Krungthep'},
    {'name': 'KufiStandardGK'},
    {'name': 'Lantinghei SC'},
    {'name': 'Lantinghei TC'},
    {'name': 'Lao MN'},
    {'name': 'Lao Sangam MN'},
    {'name': 'Libian SC'},
    {'name': 'Libian TC'},
    {'name': 'LiHei Pro'},
    {'name': 'LingWai SC'},
    {'name': 'LingWai TC'},
    {'name': 'LiSong Pro'},
    {'name': 'Lucida Bright'},
    {'name': 'Lucida Console'},
    {'name': 'Lucida Grande'},
    {'name': 'Lucida Sans Typewriter'},
    {'name': 'Luminari'},
    {'name': 'Malayalam MN'},
    {'name': 'Malayalam Sangam MN'},
    {'name': 'Marion'},
    {'name': 'Marker Felt'},
    {'name': 'Menlo'},
    {'name': 'Microsoft Sans Serif'},
    {'name': 'Microsoft YaHei'},
    {'name': 'Mishafi'},
    {'name': 'Mishafi Gold'},
    {'name': 'Monaco'},
    {'name': 'Monospace'},
    {'name': 'Mshtakan'},
    {'name': 'Muna'},
    {'name': 'Myanmar MN'},
    {'name': 'Myanmar Sangam MN'},
    {'name': 'Nadeem'},
    {'name': 'Nanum Brush Script'},
    {'name': 'Nanum Gothic'},
    {'name': 'Nanum Myeongjo'},
    {'name': 'Nanum Pen Script'},
    {'name': 'New Peninim MT'},
    {'name': 'Noteworthy'},
    {'name': 'Noto Sans'},
    {'name': 'Noto Sans Avestan'},
    {'name': 'Noto Sans Balinese'},
    {'name': 'Noto Sans Bamum'},
    {'name': 'Noto Sans Batak'},
    {'name': 'Noto Sans Brahmi'},
    {'name': 'Noto Sans Buginese'},
    {'name': 'Noto Sans Buhid'},
    {'name': 'Noto Sans Carian'},
    {'name': 'Noto Sans Cham'},
    {'name': 'Noto Sans CJK JP'},
    {'name': 'Noto Sans CJK KR'},
    {'name': 'Noto Sans CJK SC'},
    {'name': 'Noto Sans CJK TC'},
    {'name': 'Noto Sans Coptic'},
    {'name': 'Noto Sans Cuneiform'},
    {'name': 'Noto Sans Cypriot'},
    {'name': 'Noto Sans Egyptian Hieroglyphs'},
    {'name': 'Noto Sans Glagolitic'},
    {'name': 'Noto Sans Gothic'},
    {'name': 'Noto Sans Hanunoo'},
    {'name': 'Noto Sans Imperial Aramaic'},
    {'name': 'Noto Sans Inscriptional Pahlavi'},
    {'name': 'Noto Sans Inscriptional Parthian'},
    {'name': 'Noto Sans Javanese'},
    {'name': 'Noto Sans Kaithi'},
    {'name': 'Noto Sans Kayah Li'},
    {'name': 'Noto Sans Kharoshthi'},
    {'name': 'Noto Sans Lepcha'},
    {'name': 'Noto Sans Limbu'},
    {'name': 'Noto Sans Linear B'},
    {'name': 'Noto Sans Lisu'},
    {'name': 'Noto Sans Lycian'},
    {'name': 'Noto Sans Lydian'},
    {'name': 'Noto Sans Mandaic'},
    {'name': 'Noto Sans Meetei Mayek'},
    {'name': 'Noto Sans Mongolian'},
    {'name': 'Noto Sans New Tai Lue'},
    {'name': 'Noto Sans NKo'},
    {'name': 'Noto Sans Ogham'},
    {'name': 'Noto Sans Ol Chiki'},
    {'name': 'Noto Sans Old Italic'},
    {'name': 'Noto Sans Old Persian'},
    {'name': 'Noto Sans Old South Arabian'},
    {'name': 'Noto Sans Old Turkic'},
    {'name': 'Noto Sans Osmanya'},
    {'name': 'Noto Sans Phags Pa'},
    {'name': 'Noto Sans Phoenician'},
    {'name': 'Noto Sans Rejang'},
    {'name': 'Noto Sans Runic'},
    {'name': 'Noto Sans Samaritan'},
    {'name': 'Noto Sans Saurashtra'},
    {'name': 'Noto Sans Shavian'},
    {'name': 'Noto Sans Sundanese'},
    {'name': 'Noto Sans Syloti Nagri'},
    {'name': 'Noto Sans Syriac Eastern'},
    {'name': 'Noto Sans Tagalog'},
    {'name': 'Noto Sans Tagbanwa'},
    {'name': 'Noto Sans Tai Le'},
    {'name': 'Noto Sans Tai Tham'},
    {'name': 'Noto Sans Tai Viet'},
    {'name': 'Noto Sans Thaana'},
    {'name': 'Noto Sans Tifinagh'},
    {'name': 'Noto Sans Ugaritic'},
    {'name': 'Noto Sans Vai'},
    {'name': 'Noto Sans Yi'},
    {'name': 'Noto Serif'},
    {'name': 'Optima'},
    {'name': 'Oriya MN'},
    {'name': 'Oriya Sangam MN'},
    {'name': 'Osaka'},
    {'name': 'Palatino'},
    {'name': 'Palatino Linotype'},
    {'name': 'Papyrus'},
    {'name': 'PCMyungjo'},
    {'name': 'Perpetua'},
    {'name': 'Phosphate'},
    {'name': 'PilGi'},
    {'name': 'PingFang HK'},
    {'name': 'PingFang SC'},
    {'name': 'PingFang TC'},
    {'name': 'Plantagenet Cherokee'},
    {'name': 'PT Mono'},
    {'name': 'PT Sans'},
    {'name': 'PT Sans Caption'},
    {'name': 'PT Sans Narrow'},
    {'name': 'PT Serif'},
    {'name': 'PT Serif Caption'},
    {'name': 'Raanana'},
    {'name': 'Roboto'},
    {'name': 'Rockwell'},
    {'name': 'Rockwell Extra Bold'},
    {'name': 'Sana'},
    {'name': 'Sans-serif'},
    {'name': 'Sans-serif-condensed'},
    {'name': 'Sans-serif-light'},
    {'name': 'Sans-serif-thin'},
    {'name': 'Sathu'},
    {'name': 'Savoye LET'},
    {'name': 'Segoe UI'},
    {'name': 'Seravek'},
    {'name': 'Shree Devanagari 714'},
    {'name': 'SignPainter'},
    {'name': 'Silom'},
    {'name': 'Sinhala MN'},
    {'name': 'Sinhala Sangam MN'},
    {'name': 'Skia'},
    {'name': 'Snell Roundhand'},
    {'name': 'Songti SC'},
    {'name': 'Songti TC'},
    {'name': 'STFangsong'},
    {'name': 'STHeiti'},
    {'name': 'STIXGeneral'},
    {'name': 'STIXIntegralsD'},
    {'name': 'STIXIntegralsSm'},
    {'name': 'STIXIntegralsUp'},
    {'name': 'STIXIntegralsUpD'},
    {'name': 'STIXIntegralsUpSm'},
    {'name': 'STIXNonUnicode'},
    {'name': 'STIXSizeFiveSym'},
    {'name': 'STIXSizeFourSym'},
    {'name': 'STIXSizeOneSym'},
    {'name': 'STIXSizeThreeSym'},
    {'name': 'STIXSizeTwoSym'},
    {'name': 'STIXVariants'},
    {'name': 'STKaiti'},
    {'name': 'STSong'},
    {'name': 'Sukhumvit Set'},
    {'name': 'Superclarendon'},
    {'name': 'Symbol'},
    {'name': 'Tahoma'},
    {'name': 'Tamil MN'},
    {'name': 'Tamil Sangam MN'},
    {'name': 'Telugu MN'},
    {'name': 'Telugu Sangam MN'},
    {'name': 'Thonburi'},
    {'name': 'Times'},
    {'name': 'Times New Roman'},
    {'name': 'Toppan Bunkyu Gothic'},
    {'name': 'Toppan Bunkyu Midashi Gothic'},
    {'name': 'Toppan Bunkyu Midashi Mincho'},
    {'name': 'Toppan Bunkyu Mincho'},
    {'name': 'Trattatello'},
    {'name': 'Trebuchet MS'},
    {'name': 'Tsukushi A Round Gothic'},
    {'name': 'Tsukushi B Round Gothic'},
    {'name': 'Verdana'},
    {'name': 'Waseem'},
    {'name': 'Wawati SC'},
    {'name': 'Wawati TC'},
    {'name': 'Webdings'},
    {'name': 'Weibei SC'},
    {'name': 'Weibei TC'},
    {'name': 'Wingdings'},
    {'name': 'Wingdings 2'},
    {'name': 'Wingdings 3'},
    {'name': 'Xingkai SC'},
    {'name': 'Xingkai TC'},
    {'name': 'Yuanti SC'},
    {'name': 'Yuanti TC'},
    {'name': 'YuGothic'},
    {'name': 'YuKyokasho'},
    {'name': 'YuKyokasho Yoko'},
    {'name': 'YuMincho'},
    {'name': 'YuMincho +36p Kana'},
    {'name': 'Yuppy SC'},
    {'name': 'Yuppy TC'},
    {'name': 'Zapf Dingbats'},
    {'name': 'Zapfino'}
  ]
};
