export default {
  'fonts': [
    {'name': 'Andale Mono'},
    {'name': 'Arial'},
    {'name': 'Arial Black'},
    {'name': 'Arial Narrow'},
    {'name': 'Arial Rounded MT Bold'},
    {'name': 'Avant Garde'},
    {'name': 'Baskerville'},
    {'name': 'Big Caslon'},
    {'name': 'Bodoni MT'},
    {'name': 'Book Antiqua'},
    {'name': 'Bookman'},
    {'name': 'Bookman Old Style'},
    {'name': 'Brush Script MT'},
    {'name': 'Calibri'},
    {'name': 'Calisto MT'},
    {'name': 'Cambria'},
    {'name': 'Candara'},
    {'name': 'Century Gothic'},
    {'name': 'Comic Sans MS'},
    {'name': 'Consolas'},
    {'name': 'Copperplate'},
    {'name': 'Courier'},
    {'name': 'Courier New'},
    {'name': 'Didot'},
    {'name': 'Droid Sans'},
    {'name': 'Franklin Gothic Medium'},
    {'name': 'Futura'},
    {'name': 'Garamond'},
    {'name': 'Geneva'},
    {'name': 'Georgia'},
    {'name': 'Gill Sans'},
    {'name': 'Goudy Old Style'},
    {'name': 'Helvetica'},
    {'name': 'Hoefler Tex'},
    {'name': 'Impact'},
    {'name': 'KohinoorBangla-Regular'},
    {'name': 'Lucida Bright'},
    {'name': 'Lucida Console'},
    {'name': 'Lucida Grande'},
    {'name': 'Lucida Sans Typewriter'},
    {'name': 'Microsoft YaHei'},
    {'name': 'Monaco'},
    {'name': 'Monospace'},
    {'name': 'Optima'},
    {'name': 'Palatino'},
    {'name': 'Palatino Linotype'},
    {'name': 'Papyrus'},
    {'name': 'Perpetua'},
    {'name': 'Roboto'},
    {'name': 'Rockwell'},
    {'name': 'Rockwell Extra Bold'},
    {'name': 'Sans-serif'},
    {'name': 'Sans-serif-condensed'},
    {'name': 'Sans-serif-light'},
    {'name': 'Sans-serif-thin'},
    {'name': 'Segoe UI'},
    {'name': 'Tahoma'},
    {'name': 'Times'},
    {'name': 'Times New Roman'},
    {'name': 'Trebuchet MS'},
    {'name': 'Verdana'}
  ]
};
